-- ============================================
-- USER REGISTRY - DATASET DE PRUEBA
-- ORACLE 19c | ID AUTOGENERADO
-- ============================================

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Juan','Perez','juan.perez@mail.com','3001110001','jperez','1234','ADMIN','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Ana','Gomez','ana.gomez@mail.com','3001110002','agomez','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Carlos','Lopez','carlos.lopez@mail.com','3001110003','clopez','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Maria','Rodriguez','maria.rodriguez@mail.com','3001110004','mrodriguez','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Luis','Martinez','luis.martinez@mail.com','3001110005','lmartinez','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Sofia','Hernandez','sofia.h@mail.com','3001110006','shernandez','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Diego','Ramirez','diego.r@mail.com','3001110007','dramirez','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Valentina','Torres','valentina.t@mail.com','3001110008','vtorres','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Andres','Vargas','andres.v@mail.com','3001110009','avargas','1234','ADMIN','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Laura','Castro','laura.c@mail.com','3001110010','lcastro','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Camilo','Ortega','camilo.o@mail.com','3001110011','cortega','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Paula','Mendoza','paula.m@mail.com','3001110012','pmendoza','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Felipe','Rios','felipe.r@mail.com','3001110013','frios','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Daniela','Suarez','daniela.s@mail.com','3001110014','dsuarez','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Jorge','Morales','jorge.m@mail.com','3001110015','jmorales','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Natalia','Reyes','natalia.r@mail.com','3001110016','nreyes','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Sebastian','Cano','sebastian.c@mail.com','3001110017','scano','1234','ADMIN','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Juliana','Pineda','juliana.p@mail.com','3001110018','jpineda','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Mateo','Salazar','mateo.s@mail.com','3001110019','msalazar','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Carolina','Arias','carolina.a@mail.com','3001110020','carias','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('David','Mejia','david.m@mail.com','3001110021','dmejia','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Angela','Cortes','angela.c@mail.com','3001110022','acortes','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Ricardo','Navarro','ricardo.n@mail.com','3001110023','rnavarro','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Monica','Rojas','monica.r@mail.com','3001110024','mrojas','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Oscar','Quintero','oscar.q@mail.com','3001110025','oquintero','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Tatiana','Fuentes','tatiana.f@mail.com','3001110026','tfuentes','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Hugo','Escobar','hugo.e@mail.com','3001110027','hescobar','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Lorena','Nieto','lorena.n@mail.com','3001110028','lnieto','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Kevin','Parra','kevin.p@mail.com','3001110029','kparra','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Diana','Bravo','diana.b@mail.com','3001110030','dbravo','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Esteban','Ocampo','esteban.o@mail.com','3001110031','eocampo','1234','ADMIN','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Melissa','Padilla','melissa.p@mail.com','3001110032','mpadilla','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Samuel','Linares','samuel.l@mail.com','3001110033','slinares','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Vanessa','Cabrera','vanessa.c@mail.com','3001110034','vcabrera','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Cristian','Beltran','cristian.b@mail.com','3001110035','cbeltran','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Adriana','Silva','adriana.s@mail.com','3001110036','asilva','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Fernando','Peña','fernando.p@mail.com','3001110037','fpena','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Karla','Aguilar','karla.a@mail.com','3001110038','kaguilar','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Mauricio','Leal','mauricio.l@mail.com','3001110039','mleal','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Yessica','Santos','yessica.s@mail.com','3001110040','ysantos','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Brayan','Guerrero','brayan.g@mail.com','3001110041','bguerrero','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Nataly','Camacho','nataly.c@mail.com','3001110042','ncamacho','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Wilmer','Acosta','wilmer.a@mail.com','3001110043','wacosta','1234','USER','INACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Yesenia','Cardenas','yesenia.c@mail.com','3001110044','ycardenas','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Alexander','Mora','alexander.m@mail.com','3001110045','amora','1234','ADMIN','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Gloria','Restrepo','gloria.r@mail.com','3001110046','grestrepo','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Ivan','Palacios','ivan.p@mail.com','3001110047','ipalacios','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Claudia','Giraldo','claudia.g@mail.com','3001110048','cgiraldo','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Ruben','Soto','ruben.s@mail.com','3001110049','rsoto','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Patricia','Valencia','patricia.v@mail.com','3001110050','pvalencia','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Jonathan','Molina','jonathan.m@mail.com','3001110051','jmolina','1234','USER','ACTIVE');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, USERNAME, PASSWORD, ROLE, STATUS)
VALUES ('Heidy','Rincon','heidy.r@mail.com','3001110052','hrincon','1234','USER','INACTIVE');

COMMIT;